import { Country, CountryId } from "../../index";

export const countries: Country[] = [
  {
    id: 1 as CountryId,
    name: "United States",
    code: "US",
    nameRus: "США",
    flagUrl: "https://www.countryflags.io/US/flat/64.png",
    group: "F",
  },
  {
    id: 2 as CountryId,
    name: "United Kingdom",
    code: "GB",
    nameRus: "Англия",
    flagUrl: "https://www.countryflags.io/GB/flat/64.png",
    group: "A",
  },
  {
    id: 3 as CountryId,
    name: "Canada",
    code: "CA",
    nameRus: "Канада",
    flagUrl: "https://www.countryflags.io/CA/flat/64.png",
    group: "B",
  },
  {
    id: 4 as CountryId,
    name: "Germany",
    code: "DE",
    nameRus: "Германия",
    flagUrl: "https://www.countryflags.io/DE/flat/64.png",
    group: "A",
  },
  {
    id: 5 as CountryId,
    name: "France",
    code: "FR",
    nameRus: "Франция",
    flagUrl: "https://www.countryflags.io/FR/flat/64.png",
    group: "F",
  },
  {
    id: 6 as CountryId,
    name: "Australia",
    code: "AU",
    nameRus: "Австралия",
    flagUrl: "https://www.countryflags.io/AU/flat/64.png",
    group: "B",
  },
  {
    id: 7 as CountryId,
    name: "Japan",
    code: "JP",
    nameRus: "Япония",
    flagUrl: "https://www.countryflags.io/JP/flat/64.png",
    group: "C",
  },
  {
    id: 8 as CountryId,
    name: "China",
    code: "CN",
    nameRus: "Китай",
    flagUrl: "https://www.countryflags.io/CN/flat/64.png",
    group: "A",
  },
  {
    id: 9 as CountryId,
    name: "Brazil",
    code: "BR",
    nameRus: "Бразилия",
    flagUrl: "https://www.countryflags.io/BR/flat/64.png",
    group: "F",
  },
  {
    id: 10 as CountryId,
    name: "India",
    code: "IN",
    nameRus: "Индия",
    flagUrl: "https://www.countryflags.io/IN/flat/64.png",
    group: "C",
  },
];
